/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.hunter524.forlove

import java.net.URLDecoder

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}
fun main(args: Array<String>) {
    println(App().greeting)
    println("Thread is Daemon :${Thread.currentThread().isDaemon}")
    var zeroChar = '0'
    println("Show Hex:${Integer.toHexString(zeroChar.toInt())}")
    var thread = Thread {
        while (true) {
            runCatching {
                Thread.sleep(1000)
            }
        }
    }
//    thread.isDaemon = true
    thread.isDaemon = false
    thread.start()

}
