/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details take a look at the Writing Custom Plugins chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.4/userguide/custom_plugins.html
 */
/**
 * buildSrc 项目可以放置在项目中使用，也可以运行 jar 命令，生成 jar 二进制包提供其插件给其他项目使用
 */
plugins {
    `java-platform`
    `maven-publish`
}

dependencies {
    constraints {
        api("com.squareup.okio:okio:2.8.0")
    }
}
// 该任务生成 pom 文件 内部具有 dependencyManagement dependencies 标签，用于指明依赖约束
publishing {
    publications {
        create<MavenPublication>("myPlatform") {
            from(components["javaPlatform"])
        }
    }
}


